micronaut:
  application:
    name: keyManagerGrpc

datasources:
  default:
#    url: ${DB_URI:`jdbc:postgresql://localhost:5432/key-manager-grpc?currentSchema=desafio-pix`} # comentado para uso local
    url: ${DB_URI:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:`postgres`}
    password: ${DB_PASSWORD:`password`}
    schema-generate: CREATE_DROP
    dialect: ${DB_DIALECT:`POSTGRES`}


# Jpa properties
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

# external apis
itau:
  contas:
    url: ${ITAU_URL:`http://localhost:9091`}

bcb:
  pix:
    url: ${BCB_URL:`http://localhost:8082`}